{
  "login": "PaulMacLachlan",
  "id": 14798630,
  "avatar_url": "https://avatars2.githubusercontent.com/u/14798630?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/PaulMacLachlan",
  "html_url": "https://github.com/PaulMacLachlan",
  "followers_url": "https://api.github.com/users/PaulMacLachlan/followers",
  "following_url": "https://api.github.com/users/PaulMacLachlan/following{/other_user}",
  "gists_url": "https://api.github.com/users/PaulMacLachlan/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/PaulMacLachlan/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/PaulMacLachlan/subscriptions",
  "organizations_url": "https://api.github.com/users/PaulMacLachlan/orgs",
  "repos_url": "https://api.github.com/users/PaulMacLachlan/repos",
  "events_url": "https://api.github.com/users/PaulMacLachlan/events{/privacy}",
  "received_events_url": "https://api.github.com/users/PaulMacLachlan/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Paul MacLachlan",
  "company": "N SLASH A Inc.",
  "blog": "paulmaclachlan.com",
  "location": "Los Angeles - Oakland - Seattle",
  "email": null,
  "hireable": true,
  "bio": "Audio/Noise, Motion Graphics, Production Design",
  "public_repos": 29,
  "public_gists": 0,
  "followers": 2,
  "following": 12,
  "created_at": "2015-09-23T04:16:01Z",
  "updated_at": "2018-04-21T17:55:07Z"
}
